export const ImagePicker = {
  splashScreenImage: require("../../assets/splashScreen.png"),
  logoImage: require("../../assets/Images/logo.png"),
  loginScreenImage: require("../../assets/Images/Discount-Bannar.png"),
  banner1: require("../../assets/Images/Corousel-banners/1.png"),
  banner2: require("../../assets/Images/Corousel-banners/2.png"),
  banner3: require("../../assets/Images/Corousel-banners/3.png"),
  banner4: require("../../assets/Images/Corousel-banners/4.png"),
  banner5: require("../../assets/Images/Corousel-banners/5.png"),
  banner6: require("../../assets/Images/Corousel-banners/6.png"),
  weeklyDealBanner1: require("../../assets/Images/discount/banner-1.png"),
  weeklyDealBanner2: require("../../assets/Images/discount/banner-2.png"),
  weeklyDealBanner3: require("../../assets/Images/discount/banner-3.png"),
  weeklyDealBanner4: require("../../assets/Images/discount/banner-4.png"),
  weeklyDealBanner5: require("../../assets/Images/discount/banner-5.png"),
  discountImage: require("../../assets/Banner.png"),
  bestDealsImage: require("../../assets/banner2.png"),

  curatedCollection1: require("../../assets/Images/login.png"),
  curatedCollection2: require("../../assets/Images/registration.png"),
  PlaceholderImage: require("../../assets/Images/image-placeholder.png"),
  emptyCartImage: require("../../assets/Images/empty-cart.png"),
  updateProfileBgBackImage: require("../../assets/Images/update-profile-banner-back.png"),
  updateProfileBgFrontImage: require("../../assets/Images/update-profile-banner-front.png"),
  privacyPolicyBg: require("../../assets/Images/page-hero-bg-mobile.png"),
  aboutBanner: require("../../assets/Images/about-us.png"),
  aboutBanner: require("../../assets/Images/about-us.png"),
  contactBanner: require("../../assets/Images/contact-page-banner.png"),
  blogsPageBanner: require("../../assets/Images/shop-page-hero-mobile-bg.png"),
};
