const screenNames = {
  HomeScreen: "HomeScreen",
  ProductsScreen: "ProductsScreen",
  MyBucketScreen: "MyBucketScreen",
  MoreScreen: "MoreScreen",
  LoginScreen: "LoginScreen",
  OtpScreen: "OtpScreen",
  RegisterScreen: "RegisterScreen",
  ProductsDetailsScreen: "ProductsDetailsScreen",
  MoreScreen: "MoreScreen",
  WebViewScreen: "WebViewScreen",
  favouriteScreen: "favouriteScreen",
  ordersListScreen: "ordersListScreen",
  PersonalInfoScreen: "PersonalInfoScreen",
  checkoutScreen: "checkoutScreen",
  ChangePasswordScreen: "ChangePasswordScreen",
  OrderSuccessScreen: "OrderSuccessScreen",
  ForgotPasswordScreen: "ForgotPasswordScreen",
  ResetPasswordScreen: "ResetPasswordScreen",
  PrivacyScreen: "PrivacyScreen",
  TermsAndConditionsScreen: "TermsAndConditionsScreen",
  AboutusScreen: "AboutusScreen",
  ReturnPolicyScreen: "ReturnPolicyScreen",
  HelpSupportScreen: "HelpSupportScreen",
  ContactusScreen: "ContactusScreen",
  BlogsScreen: "BlogsScreen",
  DeleteAccountScreen: "DeleteAccountScreen",

};

export default screenNames;
