export const commonEntities = {
  login: "Login",
  areYouSureWantToLogout: "Are you sure you want to logout ?",
  signup: "Sign Up",
  logoutText: "Logout",
  forgotPassowrdText: "Forgot Password ?",
  dontHaveAccount: "Don't have an account?",
  alreadyHaveAccountText: "Don't have an account?",
  nextText: "NEXT",
  logoText: "Logo",
  ResetPassword: "Reset Password",
  signInAccountText: "Sign in to your Account",
  alreadyRegistered: "Already Registered ?",
  loginInAccountText: "Log in to your account",
  registerText: "Register",
  signUpText: "Create Account",
  loginText: "Log In",
  updatePassword: "Update Password",
  rememberMeText: "Remember me",
  unexpectedError: "An unexpected error occurred",
  loginWithText: "Or login with",
  googleText: "Google",
  facebooktext: "Facebook",
  agreeTermsConditonsTextfirst: "By signing up, you agree to the",
  agreeTermsConditonsTextSecond: "Terms of Service",
  agreeTermsConditonsTextThird: " Data Processing Agreement",
  forgotPwdTextSubtitle:
    "Enter your information's below or login with another account",
  search: "What are you looking....",
  weeklyDealText: "Weekly Deal",
  seeAllText: "See All",
  notAvailable: "Not available",
  whatFoodYouLoveToOrder: "What food you love to order",
  hereYourOrderSubtitle:
    "Here order your favorite foods from different categories",
  bestSellerGrocery: "Best seller grocery near you",
  bestSellerGrocerySubTitle:
    "We provide best quality & fresh grocery items near your location",

  superDiscountTitle: "SUPER DISCOUNT",
  seventyPercentOff: "70% OFF",
  discountDescrition:
    "We source and sell the freshest vegetables, carefully handpicked from trusted farmers to ensure the highest quality for you.",
  shopNow: "Shop Now",

  mySmartCartTitle: "My Smart Cart",
  bestDealsTitle: "BEST DEALS",
  salesOftheMonth: "Sale of the month",
  saleEnded: "Sale Ended!",
  curatedCollectionsTitle: "Curated Collections",
  curatedCollectionSubTitle:
    "We have categories the best quality grocery items",
  razcoAboutDescription:
    "At Razco Super Shop, we pride ourselves on delivering exceptional service and quality products to our customers. Shop with us for a seamless and satisfying experience every time!",
  moreTextHeading: "More",
  logoutText: "Log out",
  welcomeRazcoFood: "WELCOME TO RAZCOFOOD SUPER MARKET",
  weeklyDeal: "Weekly Deal",
  thankYouOrderEntitit: "Thank you. Your Order has been received.",
  copyRightDescription:"© Copyright 2025 Razco Fresh. All rights reserved."
};
