export const ImagePicker = {
  splashScreenImage: require("../../assets/Images/splash-icon.png"),
  loginScreenImage: require("../../assets/Images/login-screen.png"),
  loginImageOverlay: require("../../assets/Images/login-image-overlay.png"),
  logoIcon: require("../../assets/Images/logo-icon.png"),
  onboardingImage1: require("../../assets/Images/onboarding-image.png"),
  onboardingImage2: require("../../assets/Images/onboarding-image-2.png"),
  onboardingImage3: require("../../assets/Images/onboarding-image-3.png"),
  homeIcon: require("../../assets/Images/home-icon.png"),
  trainerIcon: require("../../assets/Images/trainers-icon.png"),
  productIcon: require("../../assets/Images/products-icon.png"),
  moreIcon: require("../../assets/Images/more-icon.png"),
  updateProfileBgBackImage: require("../../assets/Images/update-profile-banner-back.png"),
  updateProfileBgFrontImage: require("../../assets/Images/update-profile-banner-front.png"),
  eventDetailsScreenBanner: require("../../assets/Images/event-details-banner.jpg"),
  youtubeIcon: require("../../assets/Images/youtube-icon.png"),
  dummyUser: require("../../assets/Images/dummy_user.png"),
  PlaceholderImage: require("../../assets/Images/image-placeholder.png"),
};
